### ISSUE TITLE
Did you fix the cursor masked by indent-guides.nvim?

### ISSUE THREAD

**Issue by vpeopleonatank** [y9c/myneovim.lua#1]

**Comment by y9c** [comment]
Yes. By updating indent-guides.nvim and neovim to the latest version. These config files work just fine.

**Comment by y9c** [comment]
Hi @vpeopleonatank,

`indent-guides.nvim` is not stable and containing some bug. I have switch to the `Yggdroot/indentLine` plugin. Maybe you can tried this one. I might  switch back to `indent-guides.nvim` plugin once it turn stable.
